{% set name = "eip712" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ApeWorX/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d78a0b4fa1b0bb952b6d2ef554d56c725f3cc5c92624795e5446f899a9d88e0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}


requirements:
  host:
    - python {{ python_min }}
    - setuptools >=51.1.1
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - dataclassy >=0.11.1,<1
    - eth-abi >=5.1.0,<6
    - eth-account >=0.11.3,<0.14
    - eth-typing >=3.5.2,<6
    - eth-utils >=2.1.0,<6
    - hexbytes >=0.3.1,<2

test:
  imports:
    - eip712
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests
  requires:
    - hypothesis
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/ApeWorX/eip712
  summary: 'eip712: Message classes for typed structured data hashing and signing in Ethereum'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
