{% set name = "eip712" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ApeWorX/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 350754181c297d9116ad33ac68692fa52fedb610fbb49a31658c75c08cdd243f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}


requirements:
  host:
    - python >=3.8.0
    - setuptools >=51.1.1
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8.0
    - dataclassy >=0.8.2,<1
    - eth-abi >=4.1.0,<5
    - eth-account >=0.8.0,<0.9
    - eth-hash
    - eth-typing >=3.3.0,<4
    - eth-utils >=2.1.0,<3
    - hexbytes >=0.3.0,<1

test:
  imports:
    - eip712
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests
  requires:
    - hypothesis
    - pip
    - pytest

about:
  home: https://github.com/ApeWorX/eip712
  summary: 'eip712: Message classes for typed structured data hashing and signing in Ethereum'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
