{% set name = "eip712" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ApeWorX/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 957eb8a47bb94a8916f8f5efdb0f38a2a8f26e4eb77b0b2ce23a82239ede18fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}


requirements:
  host:
    - python >=3.8.0
    - setuptools >=51.1.1
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8.0
    - dataclassy >=0.8.2,<1
    - eth-abi >=5.1.0,<6
    - eth-account >=0.12.1,<0.14
    - eth-hash
    - eth-typing >=4.1.0,<5
    - eth-utils >=4.1.0,<5
    - hexbytes >=1.2.0,<2

test:
  imports:
    - eip712
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests
  requires:
    - hypothesis
    - pip
    - pytest

about:
  home: https://github.com/ApeWorX/eip712
  summary: 'eip712: Message classes for typed structured data hashing and signing in Ethereum'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
